const RULES = {
  INITIAL_DAY: 1,
  INITIAL_HP: 100,
  INITIAL_FOOD: 3,
  INITIAL_INFECTION: 10,
  INITIAL_HEAL_COUNT: 0,
  INITIAL_RESCUE_POINT: 0,

  DAILY_FOOD_CONSUMPTION: 1,
  DAILY_INFECTION_INCREASE: 3,
  STARVATION_HP_LOSS: 10,

  MIN_STAT_VALUE: 0,

  ZOMBIE_INFECTION: 100,
  CURE_HEAL_COUNT: 5,
  RESCUE_POINT_GOAL: 3,
  RESCUE_AFTER_DAY: 10,
  SURVIVAL_AFTER_DAY: 15,

  RESULT_DELAY_MS: 2000,
};

export default RULES;
